--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kimtr.
--- DateTime: 10/6/2025 1:38 PM
-- description	: 闯关活动触发器，由Relay每小时触发
-- author		: wangbin
-- datetime		: 2005-07-14

Include("\\script\\missions\\shentu\\include.lua")
function start_missions(map)
    for i = 1, getn(map) do
        index = SubWorldID2Idx(map[i]);
        if (index >= 0) then
            SubWorld = index;
            OpenMission(MISSION_MATCH);
        end
    end
end

-- 关闭地图对应的mission
function close_missions(map)
    for i = 1, getn(map) do
        index = SubWorldID2Idx(map[i]);
        if (index >= 0) then
            SubWorld = index;
            if (GetMissionV(VARV_STATE) ~= 0) then
                CloseMission(MISSION_MATCH);
            end
        end
    end
end
function StartShentu()
    -- DEBUG
    print("trigger_shentu start...");
    -- 重启missions
    for i=1, getn(tbLevelMaps) do
        close_missions(tbLevelMaps[i], MISSION_MATCH, VARV_STATE);
        start_missions(tbLevelMaps[i], MISSION_MATCH);
    end

    --闯关调整 2011.03.02
    --ChuangGuan30:KickOutAll()
    --ClearMapNpc(CHUANGGUAN30_MAP_ID)
    -- 添加计时器
    --DynamicExecute("\\script\\missions\\challengeoftime\\chuangguang30.lua", "ChuangGuan30:AddTime")
end
--OnTrigger();